docs(schemagen): Update/expand documentation on propertynaming
gregsdennis/json-everything-docs pull request #21
Opened 2024-11-25 08:01 UTC by ProbablePrime

It seems this area of the documentation was a little out of date, I have updated it!

2024-11-25 08:06 UTC, ProbablePrime commented
@dotnet-policy-service agree

2024-12-01 21:31 UTC, gregsdennis commented on _docs/schema/schemagen/schema-generation.md
> +In addition to the `[JsonPropertyName]` attribute, the configuration(`SchemaGeneratorConfiguration`) exposes a `PropertyNameResolver` delegate that allows you to define a custom method for altering p
```suggestion
In addition to the `[JsonPropertyName]` attribute, `SchemaGeneratorConfiguration.PropertyNameResolver` allows you to define a custom method for altering property names from your code into the schema. The system will adjust property names accordingly.
```

2024-12-01 21:31 UTC, gregsdennis commented on _docs/schema/schemagen/schema-generation.md
> +The `PropertyNameResolvers` static class defines a few commonly-used conventions:
```suggestion
For your convenience, the `PropertyNameResolvers` static class defines a few commonly-used conventions:
```

2024-12-01 21:32 UTC, gregsdennis commented on _docs/schema/schemagen/schema-generation.md
> +You can use them like this:
```suggestion
They can be applied directly to the configuration property:

```

2024-12-01 21:33 UTC, gregsdennis requested changes
Thanks for catching this, please see the recommendations, but I think it's good overall.

2024-12-01 22:08 UTC, ProbablePrime commented
Applied all your suggestions, thank you!

2024-12-01 22:22 UTC, gregsdennis approved these changes

2024-12-01 22:22 UTC, merged